### ISSUE TITLE
scaling off on wide images

### ISSUE THREAD

**Issue by KeithFord** [ryrych/rlightbox2#10]
you can see the problem here:
http://emilyford.com/?p=p-creative
click on the "stool design" icon
the original image is 2421 x 329
(on 1680 wide screen) it resizes to 1668 x158
the aspect ratio is wrong
time image appears squashed vertically

**Comment by astockwell** [comment]
@KeithFord I had the same issue, but realized it was because I'd changed some settings in the rlightbox js file (padding, header height, etc) and altered others with my CSS. Loading the images into the vanilla rlightbox demo fixed the issue, and iterating back into my customizations revealed the fix.
